GET http://localhost:3001/api/blogs

#############

DELETE http://localhost:3001/api/blogs/6

######################################
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdybXpyc29AZ21haWwuY29tIiwiaWQiOjEwLCJpYXQiOjE3ODU4MDgxMjB9.MY3ze17f5WcwphtRPtax8jOjReQ7LGm0wF8MWq4o44w

{
    "title": "TDD harms architecture",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html"
}

######################################
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Js with scramble eggs",
    "author": "Lou Natyck",
    "url": "https://reactpatterns.com/",
    "likes": 3
}

####################

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
}

##############


POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
   "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html"
}

###############################

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
  
  {
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
  } 

##########################
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll"
  }
########################################
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "La auditoría de Funciones de Baseline ahora está disponible en Lighthouse",
    "author": "Jeremy Wagner",
    "url": "https://web.dev/blog/baseline-lighthouse-features-audit?hl=es_419"
  }

######### POST ERROR ###########
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{

}

##### PUT ERROR #########

PUT http://localhost:3001/api/blogs/200
