GET http://localhost:3001/api/users

######################
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Gerardo Ramirez",
  "username": "grmzrso@gmail.com",
  "password": "secret"
}

################################

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Mariano Azuela",
  "username": "marAz@yandex.com",
  "password": "secret"
}

################################

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "William Shakespeare",
  "username": "willShak@gmail.com",
"password": "secret"
}

################################

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Akira Kurosawa",
  "username": "akirKu@outlook.com",
"password": "secret"
}

################################

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Robert Kappa",
    "username": "robKap@outlook.com",
    "password": "secret"
  }

#######################################
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

  {
    "name": "Emiliano Zapata",
    "username": "emiZap@yahoo.com",
    "password": "secret"
  }

#########################################
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

  {
    "name": "Gibran Khalil Gibran",
    "username": "gibKhagi@gmail.com",
    "password": "secret"
  }

#############################################

#########################################
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

  {
    "name": "Albert Camus",
    "username": "a_camus@gmail.com",
    "password": "secret"
  }

#########################################
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

  {
    "name": "Simone de Beauvoir",
    "username": "simoneB@gmail.com",
    "password": "secret"
  }  