const blogsList = () => [
  {
    title: "React patterns",
    author: "Michael Chan",
    user_id: 1,
    url: "https://reactpatterns.com/",
    created_at: new Date(),
    updated_at: new Date(),
    year: 1999,
  },
  {
    title: "Go To Statement Considered Harmful",
    author: "Edsger W. Dijkstra",
    user_id: 2,
    url: "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    created_at: new Date(),
    updated_at: new Date(),
    year: 2003,
  },
  {
    title: "Canonical string reduction",
    author: "Edsger W. Dijkstra",
    user_id: 3,
    url: "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    created_at: new Date(),
    updated_at: new Date(),
    year: 2005,
  },
  {
    title: "First class tests",
    author: "Robert C. Martin",
    user_id: 4,
    url: "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    created_at: new Date(),
    updated_at: new Date(),
    year: 2009,
  },
  {
    title: "TDD harms architecture",
    author: "Robert C. Martin",
    user_id: 5,
    url: "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    created_at: new Date(),
    updated_at: new Date(),
    year: 2000,
  },
  {
    title: "Type wars",
    author: "Robert C. Martin",
    user_id: 6,
    url: "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    created_at: new Date(),
    updated_at: new Date(),
    year: 2016,
  },
];
module.exports = blogsList();
